### GET request to example server
GET http://localhost:8080

###

### GET request
GET http://localhost:8080/api/v1/software-engineers

###

### GET request
GET http://localhost:8080/api/v1/software-engineers/user_id

###

### Send POST
POST http://localhost:8080/api/v1/software-engineers
Content-Type: application/json

{
  "firstName": "Alice",
  "lastName": "Moyo",
  "email": "alice.moyo@example.com",
  "password": "AliceDev2026!",
  "role": "ENGINEER",
  "techStack": ["Java", "Spring Boot", "PostgreSQL"]
}

###