spring.application.name=spring-boot
spring.datasource.url=jdbc:postgresql://localhost:5332/engineering
spring.datasource.username=maverick
spring.datasource.password=maverick
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=create-drop
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true